### ISSUE TITLE
Filo actors unreachable in filodb 0.7

### ISSUE THREAD

**Issue by vgkowski** [filodb/FiloDB#137] opened 2017-02-06 16:31 UTC
I am testing the master branch 0.7 with the new storage format but I get errors of unreachable actors. Compared to the 0.4 which is working fine, I get 16 actors instead of 4 and the 16 actors are getting unreachable like this first one

```
INFO [2017-02-06 14:57:19,488] ({filo-spark-akka.actor.default-dispatcher-4} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader can currently not perform its duties, reachability status: [akka.tcp://filo-spark@127.0.0.1:34833 -> akka.tcp://filo-spark@127.0.0.1:48065: Unreachable [Unreachable] (1), akka.tcp://filo-spark@127.0.0.1:34833 -> akka.tcp://filo-spark@127.0.0.1:52228: Unreachable [Unreachable] (2), akka.tcp://filo-spark@127.0.0.1:34833 -> akka.tcp://filo-spark@127.0.0.1:59560: Unreachable [Unreachable] (3), akka.tcp://filo-spark@127.0.0.1:34833 -> akka.tcp://filo-spark@127.0.0.1:60905: Unreachable [Unreachable] (4)
INFO [2017-02-06 14:57:29,865] ({filo-spark-akka.actor.default-dispatcher-20} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is auto-downing unreachable node [akka.tcp://filo-spark@127.0.0.1:34833]
```

Is there any change in 0.7 that should break the actors reachability ?

**Comment by velvia** [comment] 2017-02-06 16:49
@elppc thanks for reporting.  The major change in master for actors is that the data is automatically routed to other nodes using Akka cluster, though the number of actors should not change.  How do you know there are 16?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by elppc** [comment] 2017-02-06 16:50
I can see this in logs

```
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:44037]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:54914]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:59560]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:52228]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:41280]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:57100]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:60905]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:35448]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:58496]
 INFO [2017-02-06 14:57:35,485] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:48065]
 INFO [2017-02-06 14:57:35,486] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:59439]
 INFO [2017-02-06 14:57:35,487] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:52257]
 INFO [2017-02-06 14:57:35,487] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:34833]
 INFO [2017-02-06 14:57:35,487] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:55297]
 INFO [2017-02-06 14:57:35,487] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:52771]
 INFO [2017-02-06 14:57:35,487] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is removing unreachable node [akka.tcp://filo-spark@127.0.0.1:50405]

```

**Comment by velvia** [comment] 2017-02-06 17:37
@elppc what is your topology like?   How many executors etc. are you running?   Do you have earlier parts of the log showing initialization of the following:  NodeClusterActor, NodeCoordinatorActor

Weird that all the addresses are 127.0.0.1....   it's possible we are not returning the right strings.

**Comment by velvia** [comment] 2017-02-06 17:39
@elppc is this your Spark driver?

akka.tcp://filo-spark@10.253.51.211:33834

**Comment by elppc** [comment] 2017-02-06 17:58
It's strange that there is an initial spark stage with 1000 tasks all running on the 3 executors that are on the same host as the driver... It is related to filo-setup.scala

The spark driver on 10.253.51.211
`INFO [2017-02-06 14:56:01,513] ({pool-2-thread-4} Logging.scala[logInfo]:54) - Successfully started service 'sparkDriver' on port 52544.`

The netty server 
`INFO [2017-02-06 14:56:01,923] ({pool-2-thread-4} Logging.scala[logInfo]:54) - Server created on 10.253.51.211:42858`

The filodb driver
```
INFO [2017-02-06 14:56:13,528] ({filo-spark-akka.actor.default-dispatcher-18} BaseActor.scala[<init>]:7) - Starting class filodb.coordinator.NodeCoordinatorActor, actor Actor[akka://filo-spark/user/coordinator#-1620796199] with path akka://filo-spark/user/coordinator
INFO [2017-02-06 14:56:13,533] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@10.253.51.211:33834] is JOINING, roles [driver]
...
INFO [2017-02-06 14:56:14,499] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is moving node [akka.tcp://filo-spark@10.253.51.211:33834] to [Up]
```

Executors
`INFO [2017-02-06 14:56:18,166] ({filo-spark-akka.actor.default-dispatcher-20} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:55297] is JOINING, roles [executor]
`

` INFO [2017-02-06 14:56:18,247] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:50405] is JOINING, roles [executor]
`

```
INFO [2017-02-06 14:56:18,291] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:58496] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:18,293] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:52257] is JOINING, roles [executor]
```

```
 INFO [2017-02-06 14:56:18,499] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is moving node [akka.tcp://filo-spark@127.0.0.1:50405] to [Up]
 INFO [2017-02-06 14:56:18,500] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is moving node [akka.tcp://filo-spark@127.0.0.1:52257] to [Up]
 INFO [2017-02-06 14:56:18,500] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is moving node [akka.tcp://filo-spark@127.0.0.1:55297] to [Up]
 INFO [2017-02-06 14:56:18,505] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Leader is moving node [akka.tcp://filo-spark@127.0.0.1:58496] to [Up]
```

` INFO [2017-02-06 14:56:19,818] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:48065] is JOINING, roles [executor]`

` INFO [2017-02-06 14:56:19,857] ({filo-spark-akka.actor.default-dispatcher-6} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:59439] is JOINING, roles [executor]`

```
 INFO [2017-02-06 14:56:21,237] ({filo-spark-akka.actor.default-dispatcher-18} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:34833] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:21,238] ({filo-spark-akka.actor.default-dispatcher-5} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:57100] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:21,273] ({filo-spark-akka.actor.default-dispatcher-5} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:54914] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:21,340] ({filo-spark-akka.actor.default-dispatcher-5} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:52771] is JOINING, roles [executor]
```

```
INFO [2017-02-06 14:56:21,832] ({filo-spark-akka.actor.default-dispatcher-7} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:59560] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:21,920] ({filo-spark-akka.actor.default-dispatcher-4} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:60905] is JOINING, roles [executor]
Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:44037] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:22,006] ({filo-spark-akka.actor.default-dispatcher-5} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:52228] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:22,095] ({filo-spark-akka.actor.default-dispatcher-5} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:41280] is JOINING, roles [executor]
 INFO [2017-02-06 14:56:22,099] ({filo-spark-akka.actor.default-dispatcher-17} Slf4jLogger.scala[apply$mcV$sp]:74) - Cluster Node [akka.tcp://filo-spark@10.253.51.211:33834] - Node [akka.tcp://filo-spark@127.0.0.1:35448] is JOINING, roles [executor]
```

**Comment by velvia** [comment] 2017-02-06 19:02
Yeah the 1000 tasks is for initial Akka cluster connection.   We probably could find a better implementation, I haven’t looked up a easy way to find th number of executors (maybe use a listener).

-Evan

**Comment by velvia** [comment] 2017-02-06 19:16
Hmm so you have only 3 executors but somehow there are 16 things starting up… strange.

On the executor/worker logs, do you see something like this?   I’m curious if somehow the executor init code is being run more than once.  If there are 3 executors then there should really be just 3 executor role cluster nodes joining, not 16…

Also try changing the 1000 in FiloExecutor object (in FiloSetup.scala) to a smaller number and see if that makes a difference…  in theory it could be changed to 3 instead of 1000.  Although there is a synchronize block in the init, so it _shouldn’t_ make a difference.

thanks!

17/01/24 11:34:47 INFO FiloExecutor$: Reload of dataset coordinator actors is completed
17/01/24 11:34:47 INFO FiloExecutor$: Initializing FiloExecutor clustering by joining driver at akka.tcp://filo-spark@192.168.1.102:63572...

**Comment by elppc** [comment] 2017-02-06 20:56
I really got 4x 4 executors for this job but only 3 are running are running the first 1000 tasks. These 3 executors are located on the driver host

**Comment by velvia** [comment] 2017-02-06 23:14
Hmmm.   What kind of cluster is this?  YARN/Mesos/etc.?     What do you mean that only 3 are running but you got 4x 4 executors?  It sounds like FilODB logic on all 16 executors actually started, but some how the others died or disconnected.

LMK if Gitter would be more useful for the back and forth.  Thanks for trying this out.

**Comment by velvia** [comment] 2017-02-24 20:03
@elppc so I thought I was able to reproduce your problem on a YARN cluster, but it turns out the reason why all the executors died was because of a driver error, basically it turns out the source data had an issue.  I was using a FiloDB computed column, a date function on a string column, which doesn't work.  Any chance that is what is happening?

**Comment by velvia** [comment] 2017-02-26 01:24
@elppc I think I know the problem, do you have `spark.dynamicAllocation.enabled` set to true or false? Make sure that is false, otherwise the number of executors will grow and shrink.

**Comment by elppc** [comment] 2017-02-27 09:31
@velvia 

- my timestamp is a computed column on java.sql.Timestamp type

- dynamic allocation is not enabled but mesos shuffle is used

**Comment by velvia** [comment] 2017-02-27 15:05
What is Mesos shuffle?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by elppc** [comment] 2017-02-27 15:11
org.apache.spark.deploy.mesos.MesosExternalShuffleService

The service responsible for persisting shuffle data independantly from the executor lifecycle. It's generally used in the dynamic allocation mode but in my case dynamic allocation wasn't activated only the shuffle service

**Comment by velvia** [comment] 2017-02-27 18:08
I see.  Hmm..   well I was able to run a huge ingestion (~1 billion records) off of Spark 2.0 / master on a Cloudera CDH / YARN cluster.  I turned off dynamicAllocation and set static # of executors.   I experienced what you said when 1) there was an error, or 2) at the end of the ingestion, when everything shut down…

**Comment by velvia** [comment] 2019-01-03 18:06
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.

**Closed by velvia** 2019-01-03 18:06 UTC
